title: 新冠病毒实时新闻梳理 COVID-19 Chronicle
description: 新闻是独立思考和探索的起点，不是终点
markdown: kramdown
highlighter: rouge
github: [metadata]
encoding: utf-8
url: https://covid19-chronicle.com
google_analytics: UA-158667964-1
sass:
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap