title: COVID 2019 Chronicle
description: http://www.gov.cn/xinwen/2020-02/15/content_5479271.htm
markdown: kramdown
highlighter: rouge
github: [metadata]
plugins:
  - jekyll-seo-tag
theme: jekyll-theme-hacker